# Generated by Django 5.2.5 on 2025-08-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_photo_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='is_private',
            field=models.BooleanField(choices=[(True, 'Приватное'), (False, 'Публичное')], default=False, verbose_name='Приватность'),
        ),
    ]
