# Generated by Django 5.2.5 on 2025-08-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_photo_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_private',
            field=models.BooleanField(choices=[(True, 'Приватное'), (False, 'Публичное')], default=False, verbose_name='Приватность'),
        ),
    ]
